#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="gpsd"
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}")

s6wrap --args echo "Starting gpsd..."
s6wrap --args gpsd /dev/ttyAMA0 --foreground --passive -s 115200 -f 8N1 --listenany --nowait
