version: '3.8'

services:
  clock:
    image: ghcr.io/ifb/docker-clock:latest
    tty: true
    container_name: clock
    restart: always
    environment:
      - UBXOPTS="-f /dev/ttyAMA0 -P 18 -v 0"
    ports:
      - 2947:2947
      - 323:323/udp
      - 123:123/udp
    cap_add:
      - SYS_TIME
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/pps0:/dev/pps0
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone:ro
      - /opt/clock/drift:/var/lib/chrony/drift
      - /opt/clock/dump:/run/chrony/dump
      - /opt/clock/chrony.conf:/etc/chrony.conf:ro
    tmpfs:
      - /run:exec,size=16M
      - /tmp:size=128M
      - /var/log:size=32M
